[package]
name = "aws-tui"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = { version = "0.28.1", features = ["event-stream"] }
futures = "0.3.31"
ratatui = "0.29.0"
tokio = { version = "1.41.0", features = ["full"] }
toml = "0.5"
clap = "4.0"
